resume_analysis:
  description: >
    Analyze and extract key information from the provided resume content. Extract the following sections:
    - Summary/objective statement
    - Professional experience with key achievements
    - Educational background and degrees
    - Technical and soft skills
    - Notable projects
    - Professional certifications
    - Research publications
    - Awards received
    - Professional activities/memberships
    - Personal interests

    Resume content to analyze:
    {resume_content}

  expected_output: >
    A comprehensive structured analysis of the resume with:
    - All key sections identified and extracted
    - Most relevant information highlighted per section
    - Clear organization and formatting
    - Focus on achievements and qualifications

  agent: resume_analyzer

job_description_analysis:
  description: >
    Analyze and extract key information from the provided job description content. Extract the following sections:
    - Job title and description
    - Key requirements and responsibilities
    - Preferred qualifications and skills
    - Preferred experience and education
    - Preferred certifications and licenses
    - Preferred projects and achievements
    - Preferred activities and memberships
    - Preferred interests and hobbies
    - Preferred references
    - Preferred summary and objective

    Job description content to analyze:
    {job_description_content}

  expected_output: >
    A comprehensive structured analysis of the job description with:
    - All key sections identified and extracted
    - Most relevant information highlighted per section
    - Clear organization and formatting
    - Focus on requirements and qualifications

  agent: job_description_analyzer


validate_resume:
  description: >
    Perform a comprehensive semantic analysis comparing resume against job description requirements.
    Using the following weights for evaluation: {weights_context}

    1. Skills Analysis ({skill_match_weight}% of total score):
       - Direct Technical Skills (60%):
         * Programming languages
         * Tools and frameworks
         * Technical competencies
         * Relevant experience
         * Semantic matches
       - Soft Skills (40%):
         * Communication
         * Leadership
         * Problem-solving

    2. Experience Analysis ({experience_weight}% of total score):
       - Years of Experience (40%):
         * Total years
         * Relevant years
       - Role Relevance (60%):
         * Job title matches
         * Responsibility alignment
         * Industry experience

    3. Education Analysis ({education_weight}% of total score):
       - Degree Level (50%):
         * Required education met
         * Advanced degrees
       - Field Relevance (50%):
         * Major alignment
         * Specialization match

    4. Certifications ({certifications_weight}% of total score):
       - Required certifications
       - Additional relevant certifications
       - Professional licenses

    5. Achievements ({achievements_weight}% of total score):
       - Professional awards
       - Recognition
       - Measurable impacts

    6. Projects ({projects_weight}% of total score):
       - Relevant projects
       - Project scale
       - Technical complexity

    7. Location ({location_weight}% of total score):
       - Geographic match
       - Relocation flexibility
       - Remote work capability

    8. Industry Knowledge ({industry_weight}% of total score):
       - Domain expertise
       - Market understanding
       - Industry trends

    9. Professional Activities ({professional_activities_weight}% of total score):
       - Industry memberships
       - Conferences
       - Community involvement

    10. Publications ({publications_weight}% of total score):
        - Research papers
        - Technical articles
        - Industry contributions

    Final Score Calculation:
    - Each category will be scored based on its assigned weight
    - Detailed scoring breakdown will be provided
    - Areas for improvement will be identified

  expected_output: >
    A detailed matching analysis including:
    - Weighted score for each category
    - Overall match percentage
    - Specific strengths and gaps
    - Improvement recommendations
    - Supporting evidence for all scores
  
  agent: resume_validator

course_recommendation:
  description: >
    Search and recommend courses to address skill gaps between the candidate's resume and job requirements:
    - Analyze the resume and job description to identify key skill gaps
    - Search for relevant courses across major online learning platforms
    - For each identified skill gap:
      - Find and evaluate available courses
      - Select up to 2 best courses based on quality, reviews and learning outcomes
      - Scrape detailed course information including name, description and link
    - Focus on courses that directly address the missing skills
    - Prioritize courses with hands-on practice and real-world applications
    - Consider instructor expertise and course structure in recommendations

  expected_output: >
    A curated list of recommended courses with:
    - Clear mapping of courses to identified skill gaps
    - Maximum 2 high-quality courses per skill gap
    - Detailed course information including:
      - Course name and provider
      - Course description and learning outcomes  
      - Direct link to enroll
      - Instructor details
    - Justification for why each course was selected

  agent: course_recommender
